discord:
  - id: "subdomain"
    discord_channel: "domain"
    discord_username: "test"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/XXXXXX"

  - id: "ports"
    discord_channel: "ports"
    discord_username: "test"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/XXXXX"

  - id: "nuclei"
    discord_channel: "nuclei"
    discord_username: "test"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discord.com/api/webhooks/XXXXX"