name: bug-actions

on:
#    schedule:
#      - cron: '0 0 * * *'
# Remove both comments to run this action on daily basis.
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup Dependencies
        run: sudo apt-get install libpcap-dev # Required for Naabu

      - name: Cache Go
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setting up Tools Bugbounty
        if: steps.cache-go.outputs.cache-hit != 'true'
        env:
          GO111MODULE: on
        run: |
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest
          go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
          go install -v github.com/projectdiscovery/notify/cmd/notify@latest
          go install -v github.com/OWASP/Amass/v3/...@master
        shell: bash

## Finding Subdomains.
      - name: Running SubFinder for passive DNS enumeration
        run: |
          subfinder -all -dL input/domains.txt -config config/subfinder-config.yaml -o output/subfinder_subdomains.txt
        shell: bash

      - name: Running Ammass Passive
        run: | 
          amass enum -df input/domains.txt -passive -config config/amass-config.ini -brute | tee output/amass_subdomains.txt
        shell: bash

      - name: Sort Subdomain
        run: |
          cat output/*_subdomains.txt | sort -u | tee output/passive_subdomains.txt
        shell: bash

      - name: Running dnsx for valid DNS filtering 
        run: |
          dnsx -l output/passive_subdomains.txt -t 50 | tee output/active_subdomains.txt
        shell: bash

      - name: Running naabu to check top 100 ports
        run: |
          naabu -l output/active_subdomains.txt  -rate 10000 -top-ports 1000 | tee output/active_ports.txt
        shell: bash

      - name: Running httpx for HTTP webservers probbing
        run: |
          httpx -l output/active_ports.txt -o output/active_urls.txt 
        shell: bash

      - name: Nuclei Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: output/active_urls.txt
          output: output/nuclei_output.txt
          
      - name: Sorting the output results
        run: |
          find output -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add output/passive_subdomains.txt
          git add output/active_subdomains.txt
          git add output/active_ports.txt
          git add output/active_urls.txt
          git add output/nuclei_output.txt

      - name: Send To notify
        run: |
          notify -i output/active_subdomains.txt -pc config/notify-config.yaml -bulk -id subdomain
          notify -i output/active_ports.txt -pc config/notify-config.yaml -bulk -id ports
          notify -i output/nuclei_output.txt -pc config/notify-config.yaml -bulk -id nuclei
        shell: bash

      - name: Commit results to Github
        run: |
          git config --local user.email "3xploitdb2067@gmail.com"
          git config --global user.name "blacktool"
          git commit -m "PD-Actions report" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
